### ISSUE TITLE
[BUG] CSGO closes upon running the cheat

### ISSUE THREAD

**Issue by xtremegamer1** [TheRatCode/RatPoison#762] opened 2021-05-03 23:10 UTC
**Describe the bug**

**To Reproduce**
Add steps on how to reproduce this issue/bug, if you don't this issue will be closed and won't be looked into.

**Pictures/Videos**
If applicable, add screenshots or link a video to help explain your problem.

**Comment by sotakoira** [comment] 2021-05-03 23:11
not a bug, hazedumper is outdated. wait until morning

**Comment by Jasmitt** [comment] 2021-05-03 23:23
not a bug. be patient. wait for offset update.

**Comment by xtremegamer1** [comment] 2021-05-04 00:21
> not a bug. be patient. wait for offset update.

Bruh they change the offsets every update? So how can I replace the files without having to recompile once hazedumper is updated

**Comment by terragady** [comment] 2021-05-04 00:34
> 
> 
> > not a bug. be patient. wait for offset update.
> 
> Bruh they change the offsets every update? So how can I replace the files without having to recompile once hazedumper is updated

what is wrong with recompiling?

**Comment by sotakoira** [comment] 2021-05-04 00:41
> 
> 
> > not a bug. be patient. wait for offset update.
> 
> Bruh they change the offsets every update? So how can I replace the files without having to recompile once hazedumper is updated

Once hazedumper gets updated just restart your RatPoison beta.

**Comment by sotakoira** [comment] 2021-05-04 01:12
For extremely impatient people.

Go to:  RatPoison/src/main/kotlin/rat/poison/game/offsets/EngineOffsets.kt 

Find: ` val dwbSendPackets = parseOffset()`
Replace with:  `val dwbSendPackets = 882378`

Delete build folder, recompile.

**Comment by terragady** [comment] 2021-05-04 01:22
> 
> 
> For extremely impatient people.
> 
> Go to: RatPoison/src/main/kotlin/rat/poison/game/offsets/EngineOffsets.kt
> 
> Find: ` val dwbSendPackets = parseOffset()`
> Replace with: `val dwbSendPackets = 882378`
> 
> Delete build folder, recompile.

or change the provider in parseOffset function even to something like this 
[https://github.com/JokinAce/CSGO-Offsets]

**Comment by sotakoira** [comment] 2021-05-04 01:23
> 
> 
> > For extremely impatient people.
> > Go to: RatPoison/src/main/kotlin/rat/poison/game/offsets/EngineOffsets.kt
> > Find: ` val dwbSendPackets = parseOffset()`
> > Replace with: `val dwbSendPackets = 882378`
> > Delete build folder, recompile.
> 
> or change the provider in parseOffset function even to something like this
> []https://github.com/JokinAce/CSGO-Offsets

the point is none of those are updated right now. if you wait those 7 hours hazedumper should be updated, the repo that is used in beta versions.

**Comment by terragady** [comment] 2021-05-04 01:25
oh ok, i thought JokinAce is quicker and that it has up to date offset, my bad

**Comment by akototanga** [comment] 2021-05-04 06:11
so no cheat for a while now?? :(

**Comment by chintuthrowaway** [comment] 2021-05-04 07:32
> For extremely impatient people.
> 
> Go to: RatPoison/src/main/kotlin/rat/poison/game/offsets/EngineOffsets.kt
> 
> Find: ` val dwbSendPackets = parseOffset()`
> Replace with: `val dwbSendPackets = 882378`
> 
> Delete build folder, recompile.

i am stupid, so when you say recompile, what do you mean?

**Comment by sotakoira** [comment] 2021-05-04 07:34
> i am stupid, so when you say recompile, what do you mean?

run the build script/installer

**Comment by chintuthrowaway** [comment] 2021-05-04 08:12
the issue is fixed now i heard, so do i just run ratpoison, or do i have to change something?

**Comment by sotakoira** [comment] 2021-05-04 08:17
> the issue is fixed now i heard, so do i just run ratpoison, or do i have to change something?

repos are still outdated, if hazedumper updates then just run the cheat and correct offset will be used.

**Comment by mountaincastle47** [comment] 2021-05-04 08:29
so uh any video of how to fix this issue?

**Comment by chintuthrowaway** [comment] 2021-05-04 08:50
> > the issue is fixed now i heard, so do i just run ratpoison, or do i have to change something?
> 
> repos are still outdated, if hazedumper updates then just run the cheat and correct offset will be used.

so i just wait until hazedumper game update says the current date, and then i run rp-master?

**Comment by sotakoira** [comment] 2021-05-04 08:52
> so i just wait until hazedumper game update says the current date, and then i run rp-master?

beta or we-do-a-little.
master uses a repo that is even less often updated.

**Comment by sotakoira** [comment] 2021-05-04 09:14
https://github.com/frk1/hazedumper/commits/master

hazedumper has been updated, users of **beta** branch can now play without crashing.

**Closed** 2021-05-04 09:28 UTC
