### ISSUE TITLE
Crashing with new update [BUG]

### ISSUE THREAD

**Issue by vshazer** [TheRatCode/RatPoison#774] opened 2021-05-07 01:17 UTC
As soon as you log into a session, it crashes your game.

**Comment by thefuckingrap** [comment] 2021-05-07 01:18
![image](https://user-images.githubusercontent.com/68853992/117384235-85f78380-aeb0-11eb-8fe6-bc26265b9e7b.png)

**Comment by sotakoira** [comment] 2021-05-07 01:18
duplicate of #773

**Closed** 2021-05-07 02:46 UTC
